### ISSUE TITLE
Update Installation Docs for Backend

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#1664]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

Please update the Installation Docs for following:
- [ ] Generic Installation Instructions. Please see [this](https://github.com/fossasia/open-event-server/blob/development/docs/installation/basic.md) for reference.
- [ ] Installation on Linux/Unix using Virtualenv. Please see [this](https://github.com/fossasia/open-event-server/blob/development/docs/installation/local.md) for reference. 
- [ ] Installaion on Windows or Vagrant Installation. Please see [this](https://github.com/fossasia/open-event-server/blob/development/docs/installation/vagrant.md) for reference.
- [ ] Deployment on Heroku. Please see [this](https://github.com/fossasia/open-event-server/blob/development/docs/installation/heroku.md) for reference.
- [ ] Deployment on Docker. Please see [this](https://github.com/fossasia/open-event-server/blob/development/docs/installation/docker.md) for reference.

1. Please **open separate Issue** for respective Installation docs.
2. Installation docs should be placed [`api/docs/installation`](https://github.com/fossasia/badgeyay/tree/development/api/docs/installation).
3. Please update the link of installation docs in the [`README`](https://github.com/fossasia/badgeyay/blob/development/api/README.md)
3. Every Installation doc should contain a good quality screenshot for every step mentioned.
4. Use Github `Markdown` uniformly for formatting the Installation steps.

**Comment by prabhupant** [comment]
can I get this issue assigned to me?

**Comment by abishekvashok** [comment]
@peabhupant go on

**Comment by ParthS007** [comment]
@prabhupant  Please read the points that I have mentioned in the Issue.

> Please open **separate Issue** for respective Installation docs.

You can create one and start working on it. :+1:

**Comment by prabhupant** [comment]
@ParthS007 yeah sure...i'm working on it :+1:

**Comment by rupav** [comment]
@ParthS007 one should add instructions to install `bower` too in frontend before one can run `bower install` globally.

**Comment by PawanLakhwani** [comment]
can i work on this.

**Comment by ParthS007** [comment]
Yes @PawanLakhwani , Add Installation on Windows or Vagrant. Please see [this](https://github.com/fossasia/open-event-server/blob/development/docs/installation/vagrant.md) for reference.

**Comment by parammittal16** [comment]
@ParthS007 can I work on this to add Installation on Windows or Vagrant?

**Comment by ParthS007** [comment]
Yes @parammittal16 , Please go ahead with it :+1:

**Comment by yatri1609** [comment]
@ParthS007 Can I work on this issue?

**Comment by kushthedude** [comment]
> @ParthS007 Can I work on this to add Installation on windows and Vagrant ?

Please go ahead @yatri1609

**Comment by remote007** [comment]
Hi @kushthedude .. is this issue open for contribution ?
