### ISSUE TITLE
V.2: Planned roadway for version 2

### ISSUE THREAD

**Issue by kushthedude** [fossasia/badgeyay#2168]
**For the development of V.2, TDD(Test Driven Development) approach should opt**

- [ ] Implement **Django Server with API-Blueprint using Swagger or Apiary.**
- [ ] Implement **ReactJS FrontEnd**, Framework can be decided later on.
- [ ] Implement CD and other Cloud Functions

**Comment by kushthedude** [comment]
@iamareebjamal Your thoughts on the development life cycle.

**Comment by codedsun** [comment]
@kushthedude I want to get involved also.  let's move forward! Also, i would request to divide the major tasks with minor tasks(issues) so that everyone can take this and proceed.

**Comment by godcrampy** [comment]
I'd like to work on the ReactJs part. I've sent a PR for the initial ReactJs setup.

**Comment by iamareebjamal** [comment]
@godcrampy It'll be worked upon after development of backend

**Comment by iamareebjamal** [comment]
@kushthedude First, let's list the feature requirement of the server to see what path should be taken

What should be the capability of the server? What features should it have at the end of development.

For example, 
1. Have an API for use with client apps which does following things
2. Have a website with these facilities
3. Have these features

**Comment by codedsun** [comment]
@kushthedude @iamareebjamal As we have done the initial setup of django, now when and how shall be the next step be done for discussing db model structure ?

**Comment by iamareebjamal** [comment]
What models we had in previous app

**Comment by abishekvashok** [comment]
Let me join in as well. Let's go forward.

**Comment by codedsun** [comment]
@iamareebjamal I am moving with creating basic login functionality

**Comment by iamareebjamal** [comment]
> What models we had in previous app?

First, we need to design the DB

**Comment by kushthedude** [comment]
I am checking onto it, also this time we need to include payments module
too.

**Comment by iamareebjamal** [comment]
That will be done progressively

**Comment by codedsun** [comment]
How we are going to design the DB? Either through a meeting, discussion or do I list the models used earlier in the app here? or design the DB as done earlier ?How we should proceed? @iamareebjamal

**Comment by iamareebjamal** [comment]
List the models

**Comment by codedsun** [comment]
![image](https://user-images.githubusercontent.com/20026440/68473042-f08e1b80-0247-11ea-9687-176699d3871e.png)

**Comment by iamareebjamal** [comment]
And the columns?

**Comment by codedsun** [comment]
uploading in few mins

**Comment by codedsun** [comment]
Table 

1. Badges
![image](https://user-images.githubusercontent.com/20026440/68475982-8b3e2880-024f-11ea-8bb0-95d108b31f0d.png)

2. File
![image](https://user-images.githubusercontent.com/20026440/68476002-98f3ae00-024f-11ea-8a7b-2c5cee90ef68.png)

3. Modules
![image](https://user-images.githubusercontent.com/20026440/68476022-a741ca00-024f-11ea-8fd1-6cacdfb2b66a.png)

4. Permissions
![image](https://user-images.githubusercontent.com/20026440/68476043-b45eb900-024f-11ea-9232-5659933badb8.png)

5. Reset Password Token
![image](https://user-images.githubusercontent.com/20026440/68476067-c2acd500-024f-11ea-9e1e-aa8c232d5d0a.png)

6. Settings
![image](https://user-images.githubusercontent.com/20026440/68476115-e2dc9400-024f-11ea-82e8-033a323517ca.png)

7. SocialContent
![image](https://user-images.githubusercontent.com/20026440/68476145-fab41800-024f-11ea-8e7b-694f2d44f5ed.png)


8. User
![image](https://user-images.githubusercontent.com/20026440/68476156-03a4e980-0250-11ea-86f9-e65f0b2caa54.png)

9. Utilities
![image](https://user-images.githubusercontent.com/20026440/68476189-10c1d880-0250-11ea-9ec1-dbe840e0225e.png)

**Comment by codedsun** [comment]
@iamareebjamal Done

**Comment by iamareebjamal** [comment]
What do we want to retain from previous site?

**Comment by codedsun** [comment]
@kushthedude Please answer this, I am a beginner here.

**Comment by codedsun** [comment]
@kushthedude inputs please, so that we can proceed forward. Thanks

**Comment by codedsun** [comment]
@iamareebjamal Please tell me how do I do this?  I have not received any response till now. How do we move forward

**Comment by iamareebjamal** [comment]
Add auth to new site for now

**Comment by codedsun** [comment]
@iamareebjamal What is the next step?

**Comment by codedsun** [comment]
@iamareebjamal What is the next step after auth?

**Comment by kushthedude** [comment]
Planning of models

**Comment by codedsun** [comment]
https://github.com/fossasia/badgeyay/issues/2168#issuecomment-551724198


@kushthedude Need your reply here for the models

**Comment by codedsun** [comment]
@kushthedude If you can help, finalising what we want to retain from previous site, we can move forward. Also let's see what @iamareebjamal says.

**Comment by championpaddler** [comment]
@iamareebjamal  I will also like to contribute.

**Comment by gabru-md** [comment]
Hi I'd like to join this discussion as well. In case you require some help regarding the previous site I'll be happy to provide the insight as much as I can.
:smiley:

**Comment by codedsun** [comment]
@gabru-md Thanks a lot. We need to plan the models now. Please help me to get it done

**Comment by abishekvashok** [comment]
> We need to plan the models now. Please help me to get it done

What are the current plans?

**Comment by codedsun** [comment]
@abishekvashok https://github.com/fossasia/badgeyay/issues/2168#issuecomment-558678170

**Comment by gabru-md** [comment]
so for the models, we shall have to first identify what is needed to be stored in db. You have a snapshot of the previous model that we were running back when we first created badgeyay. What are the proposed plans that you plan on adding or removing?

**Comment by codedsun** [comment]
@gabru-md Yeah I added in the thread here about the models. @kushthedude Kindly tell us what models do we need here and what we want to retain from the previous site. So that we can move forward at a fast pace.

**Comment by codedsun** [comment]
@kushthedude If time allows please do make this task also proceed forward. Thanks

**Comment by maze-runnar** [comment]
@codedsun i think every thread from previous model should be collected to one place, is there any problem in using same fields as previous models have ?

**Comment by maze-runnar** [comment]
@codedsun when the next step would be finalize? i love to work on Django, So i want to be here more .

**Comment by codedsun** [comment]
@maze-runnar : I am stuck here https://github.com/fossasia/badgeyay/issues/2168#issuecomment-551724198 

I have not worked with this previously so I dont' know the answer what to retain in the next.


>@codedsun i think every thread from previous model should be collected to one place, is there any problem in using same fields as previous models have ?

The models are listed here

https://github.com/fossasia/badgeyay/issues/2168#issuecomment-551696414


@iamareebjamal @kushthedude - If we can take this forward it would be great 👍

**Comment by abishekvashok** [comment]
User accounts to the minimum point, if it's not possible then we can proceed with a fresh start :)

**Comment by iamareebjamal** [comment]
The point is that we can neither migrate old data nor start fresh unless someone knows the end goal of what it should look like, what are the features required, what is the roadmap. The points listed in this issue are vague and tech specific. We need specifications and end goal of the server. I don't know that and hence can't help move it forward unless someone else who knows the current project helps. I won't have enough time to dig through current project and see its nooks and crannies to port over. I can just comment on technical details on how to implement a certain functionality. I'm of no use if no one knows what functionality to develop

**Comment by abishekvashok** [comment]
Okay, what we want is basically this:
A server API with minimal functionality of user authentication (again optional) and badge generation in Django. Then we can proceed with more options later.

A frontend to act as an interactive interface for the API in ReactJS

**Comment by abishekvashok** [comment]
I can do this if no one can't do it :)

**Comment by maze-runnar** [comment]
@abishekvashok  it was a part of the discussion https://github.com/fossasia/badgeyay/pull/2176#issuecomment-558141572
@iamareebjamal has said that we should go with Django templating as the project is not that UI intensive to use a separate frontend.

**Comment by PragatiVerma18** [comment]
@kushthedude I would like to work on the Django part and would like to contribute a Users API that can help login/signup using Django Rest Framework, to begin with until the models are decided. After I have made the APIs, we can have the frontend integrated so that at least for beginning, login signup is functional, then we will keep adding features. Would that be a good plan to go with?

**Comment by iamareebjamal** [comment]
We'll be using Django Templates, not separate frontend

**Comment by PragatiVerma18** [comment]
Okay, so are we not going to have the frontend and backend hosted to two different domains, we are just going to make a Django app inside our Django project for the backend and a separate folder for frontend? If so, we can use templated js snippets? Read about it here: [hackernoon](https://hackernoon.com/reconciling-djangos-mvc-templates-with-react-components-3aa986cf510a)

**Comment by iamareebjamal** [comment]
No JS needed for now. It's a pretty simple site. JS should be used for enhancements, like in github. The site you are writing this comment on is server side rendered and much better than any SPA I have used. What little enhancements they use JS for is fine. And wherever they use client-side rendering, it's always worse experience than server render. JS rendering should be used where you have highly dynamic UI and basically cannot do server render anyway - like infinite scrolling feeds in facebook/twitter with mariands of post types and dynamic media like picture albums/video. JS rendering anywhere else is not only unneeded but way poorer experience than server render. And then everyone still ends up rendering it on server using Next/Nuxt/Fastboot. Why go full circle and still do what we wanted to avoid in the first place, and in a much worse way?

**Comment by PragatiVerma18** [comment]
Okay, I understand.

**Comment by siddhantvirus** [comment]
since there have been no updates since January is there anything could work on ? Either React or the CD and Cloud Part ?

**Comment by PragatiVerma18** [comment]
@iamareebjamal @maze-runnar @kushthedude is there something to work on in Django or React? or are you going to continue with Ember and Flask? Please clarify the state of this project.

**Comment by iamareebjamal** [comment]
Only Django. And our focus is not on the project right now https://gitter.im/fossasia/fossasia?at=5f78a76a6e0eb8446962511d
