### ISSUE TITLE
Refactor Badgeyay

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#489]
**Todo**
- [x] Backup current repo and move under V1
- [ ] Merge `rest-api` branch
- [ ] Delete `rest-api`
- [x] Delete `gci-frontend-task`
- [x] Seperate `frontend` and `backend` folder

**Comment by ParthS007** [comment]
working on back end part 👍

**Comment by abishekvashok** [comment]
@vaibhavsing97 done. I've deleted the branch. It was merged by @ParthS007

**Comment by vaibhavsingh97** [comment]
Still, I will send one PR and that will delete redundant files. Thanks

**Comment by abishekvashok** [comment]
@vaibhavsing97 as I can see that many files exist in the backend as well that needs to be removed. I've open an issue for that. Pls assign on that issue.
