### ISSUE TITLE
Admin Module - Master Issue

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#841]
As discussed in the meeting, we need `admin` section where admin can manage basic and advance settings to ease users to generate badges.

1. Add `Admin` module in current project
    - [ ] Add different section like Admin, Badges, Users, Permissions, Reports, Settings, etc in frontend
    - [ ] Add basic models in current system for superadmin 
2.  `Main` section 
     - [ ] Different analytics
       - [ ]  different number of badge genrated
       - [ ]  total number of users, unverified users, verified users, no. of admins, etc
       - [ ]  no of mail sent, etc
3. `Settings` section
    - [ ] Add models for storing credentials for Google, twitter, Firebase, etc
    - [ ] Add `Mail` configuration  in setting section
    - [ ] Add option to enable and disable different badge sizes
    - [ ] Add option to add analytics in settings section
    - [ ] Add option to configure payment gateways
4. `Permission` section
    - [ ] Edit Different Roles for user
5. `Content` section
    - [ ] Add/Edit Different Social links on web app
    - [ ] Add Different pages 
    - [ ] Provide different translation to users

I will update this master issue after I explore  [Open Event](https://github.com/fossasia/open-event-legacy) admin dashboard more.

Cc @djmgit @mariobehling

**Comment by vaibhavsingh97** [comment]
Cc @djmgit @mariobehling

**Comment by djmgit** [comment]
@vaibhavsingh97 looks good to me, a lot of work need to be done on the admin section. So let's get it done steadily.
@mariobehling please have a look, in case you want to add or remove something.

**Comment by gabru-md** [comment]
closing this
